### PR TITLE
Fixes issue #1

### PR DESCRIPTION
**Pull request by ryn1x**
Fixes issue #1. Brought back some files that were probably deleted on accident and updated META6. Module now installs and works on my system.

### CODE REVIEW

**Comment by nige123** [comment]
JMP::System is a file that belongs to the previous version of jmp.

I think the solution is to install the latest version with:

`shell> zef upgrade jmp`

**Comment by nige123** [comment]
Thank you for trying to fix the issue.

**Comment by nige123** [comment]
Actually on close inspection of the code I can see there is a reference to JMP::System and JMP::Template in JMP::Config.

I will remove the reference and update the tests.

**Comment by ryn1x** [comment]
Version 2.1 fixes this. Thanks!

**Pull request closed without merging**
